---
language: ruby

script: bundle exec rake

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libarchive-dev
  - gem update --system
  - gem install bundler

rvm:
  - 2.1

notifications:
  email:
    recipients:
      - development+travis-opener@olery.com

    on_success: change
    on_failure: change

branches:
  only:
    - master
